### ISSUE TITLE
E621 site issues.

### ISSUE THREAD

**Issue by zwagoth** [anon-a/DBooru#20]
Hey there,

You project currently violates a bunch of the API rules for e621 and has gotten a few people banned from the site.

I'm contacting you in hopes that you will make corrections to your project so that it complies with the API guidelines. The guidelines and other API information can be found here https://e621.net/help/show/api

- This project impersonates a web browser, which is against the e621 API usage terms. The user agent submitted must comply with the user-agent rules for API usage, which can be seen on the wiki page for the API.
- This project does not sanity check HTTP response codes such as 404, 403, 503, 500 etc. This causes it to continue to make requests even when it will never properly work. Both 400 and 500 range errors should be an abort condition, because the site is not willing to serve the requests made.
- The exit condition for your loops is not valid so it makes infinite requests.
- E621 has a maximum page count of 750 and page access above this will always fail. There is a work around listed on the API documentation wiki.
- When threaded the delay between requests is not honored properly and we've seen people making as many as 50 requests a second to the server. This needs to be fixed.
- E621 will always return valid JSON for .json requests unless something has gone terribly wrong and you're hitting a hard error condition. Please use the python `json` module to parse this data and handle invalid input as an exit condition.

Thank you for your time and I hope that you will make these changes.

**Comment by anon-a** [comment]
Fixed in #21
